@hostname = http://localhost:8080


### Post request OK should return JSON
POST {{hostname}}/create
Content-Type: application/json

{
  "username": "user1",
  "password": "iwanttojoinwheelhub"
}

### Post request - not accepting missing fields
POST {{hostname}}/create
Content-Type: application/json

{
  "username": "user2",
}

### Post request - not saving additional fields
POST {{hostname}}/create
Content-Type: application/json

{
  "username": "user3",
  "password": "iwanttojoinwheelhub",
  "confirmation": "extrafield",
  "hint": "extrafield"
}

## Post request - not accepting invalid format
POST {{hostname}}/create
Content-Type: application/json

{
  "username": 1234,
  "password": "iwanttojoinwheelhub"
}